steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      curl -Lo /usr/local/bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
      chmod +x /usr/local/bin/skaffold && \
      skaffold build --file-output artifacts.json

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
    - 'deploy'
    - 'releases'
    - 'create'
    - 'release-$BUILD_ID'
    - '--region'
    - 'asia-northeast1'
    - '--delivery-pipeline'
    - 'pfe-cicd'
    - '--build-artifacts'
    - 'artifacts.json'
    - '--skaffold-file'
    - 'skaffold.yaml'
    - '--source'
    - '.'