apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: random-pets
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - name: random-pets
          image: random-pets